apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  type: LoadBalancer   # TEMPORARY for testing
  selector:
    app: Cluster ip
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
