apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  type: ClusterIP   # changed from ClusterIP
  selector:
    app: laravel-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
