name: CI - Build, Push Docker image, and Update Helm Chart

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'helm/laravel-web-app-chart/values.yaml'  # 🚀 Prevents infinite loop
  workflow_dispatch:

env:
  IMAGE_NAME: rk9718471899/laravel-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_SEC_TOKEN }}

      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{ needs.build-and-push.outputs.image_tag }}"/' helm/laravel-web-app-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "rk5267124@gmail.com"
          git config --global user.name "Rjesh2006"
          git add helm/laravel-web-app-chart/values.yaml
          git commit -m "Update tag in Helm chart to ${{ needs.build-and-push.outputs.image_tag }}"
          git push
